//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDExt.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDExt.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Next Designのエクステンションを作成できるユーティリティです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionCreateExtensionUtility0 {
            get {
                return ResourceManager.GetString("DescriptionCreateExtensionUtility0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトのテンプレートをインストールします。最初に実行して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionInstallCommand0 {
            get {
                return ResourceManager.GetString("DescriptionInstallCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダにNext Design V3.1向けのエクステンションのプロジェクトを作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNew31Command0 {
            get {
                return ResourceManager.GetString("DescriptionNew31Command0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダにExtensionPointsライブラリを用いたNext Design V3.1向けのエクステンションのプロジェクトを作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNew31ExtpCommand0 {
            get {
                return ResourceManager.GetString("DescriptionNew31ExtpCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダにNext Design V4.0向けのエクステンションのプロジェクトを作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNew4Command0 {
            get {
                return ResourceManager.GetString("DescriptionNew4Command0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダにExtensionPointsライブラリを用いたNext Design V4.0向けのエクステンションのプロジェクトを作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNew4ExtpCommand0 {
            get {
                return ResourceManager.GetString("DescriptionNew4ExtpCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダに最新のNext Design向けのエクステンションのプロジェクトを作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNewCommand0 {
            get {
                return ResourceManager.GetString("DescriptionNewCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成プロジェクト名を指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNewCommandProjectName0 {
            get {
                return ResourceManager.GetString("DescriptionNewCommandProjectName0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダにExtensionPointsライブラリを用いた最新のNext Design向けのエクステンションのプロジェクトを作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionNewExtpCommand0 {
            get {
                return ResourceManager.GetString("DescriptionNewExtpCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクステンションをパッケージ化します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPackCommand0 {
            get {
                return ResourceManager.GetString("DescriptionPackCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビルド構成を指定します。`Debug`または`Release`を指定して下さい。未指定の場合は `{0}` です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPackCommandBuildConfig1 {
            get {
                return ResourceManager.GetString("DescriptionPackCommandBuildConfig1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成したパッケージを指定フォルダにもコピーします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPackCommandCopyDir0 {
            get {
                return ResourceManager.GetString("DescriptionPackCommandCopyDir0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作の対象となるNext Designのバージョンです。未指定の場合は `{0}` です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPackCommandNDVersion1 {
            get {
                return ResourceManager.GetString("DescriptionPackCommandNDVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成したパッケージの格納フォルダを指定します。未指定の場合は `{0}` です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPackCommandOutputDir1 {
            get {
                return ResourceManager.GetString("DescriptionPackCommandOutputDir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロジェクトのディレクトリを指定します。未指定の場合は現在のディレクトリ以下を探索して実行します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPackCommandProjectDir0 {
            get {
                return ResourceManager.GetString("DescriptionPackCommandProjectDir0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Design V3.1向けのExtensionPointsライブラリを用いたエクステンションです（推奨）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionTemplateExtpStandardExtensionV31_0 {
            get {
                return ResourceManager.GetString("DescriptionTemplateExtpStandardExtensionV31_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Design V4.0向けのExtensionPointsライブラリを用いたエクステンションです（推奨）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionTemplateExtpStandardExtensionV4_0 {
            get {
                return ResourceManager.GetString("DescriptionTemplateExtpStandardExtensionV4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Design V3.1向けの標準のエクステンションです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionTemplateStandardExtensionV31_0 {
            get {
                return ResourceManager.GetString("DescriptionTemplateStandardExtensionV31_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Design V4.0向けの標準のエクステンションです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionTemplateStandardExtensionV4_0 {
            get {
                return ResourceManager.GetString("DescriptionTemplateStandardExtensionV4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトのテンプレートをアンインストールします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionUninstallCommand0 {
            get {
                return ResourceManager.GetString("DescriptionUninstallCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   csprojファイルに作成者（`Authors`）を指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAuthorsNotSpecified0 {
            get {
                return ResourceManager.GetString("ErrorAuthorsNotSpecified0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド `{0} {1}` の実行に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCommandExecutionFailed2 {
            get {
                return ResourceManager.GetString("ErrorCommandExecutionFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   csprojファイルで説明（`Description`）を指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDescriptionNotSpecified0 {
            get {
                return ResourceManager.GetString("ErrorDescriptionNotSpecified0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHeader1 {
            get {
                return ResourceManager.GetString("ErrorHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nuget.exe が見つからないため、パッケージ処理が実行できませんでした。https://www.nuget.org/downloads から nuget.exe をダウンロードし、適切なフォルダーに保存して、そのフォルダーを PATH 環境変数に追加してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNugetNotFound0 {
            get {
                return ResourceManager.GetString("ErrorNugetNotFound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   csprojファイルにパッケージId（`PackageId`）を指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorPackageIdNotSpecified0 {
            get {
                return ResourceManager.GetString("ErrorPackageIdNotSpecified0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトファイルがすでに存在しているため処理を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProjectFileAlreadyExists0 {
            get {
                return ResourceManager.GetString("ErrorProjectFileAlreadyExists0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトファイルの作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProjectFileCreationFailed0 {
            get {
                return ResourceManager.GetString("ErrorProjectFileCreationFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクステンションのプロジェクトファイル(csproj)が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProjectFileNotFound0 {
            get {
                return ResourceManager.GetString("ErrorProjectFileNotFound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   csprojファイルでパッケージバージョンが指定されていません。バージョン（`Version`）を指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorVersionNotSpecified0 {
            get {
                return ResourceManager.GetString("ErrorVersionNotSpecified0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderBuildProject0 {
            get {
                return ResourceManager.GetString("HeaderBuildProject0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy nupkg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderCopyNupkg0 {
            get {
                return ResourceManager.GetString("HeaderCopyNupkg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating Next Design Extension Solution &amp; Project
        ///
        ///Project Name: &apos;{0}&apos;
        ///Template Type: &apos;{1}&apos;
        ///Template Description: &apos;{2}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderCreatingExtensionProjectDetails3 {
            get {
                return ResourceManager.GetString("HeaderCreatingExtensionProjectDetails3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderDone0 {
            get {
                return ResourceManager.GetString("HeaderDone0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートをインストールしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderInstallingTemplates0 {
            get {
                return ResourceManager.GetString("HeaderInstallingTemplates0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Packaging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderPackaging0 {
            get {
                return ResourceManager.GetString("HeaderPackaging0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートをアンインストールしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTemplateUninstalling0 {
            get {
                return ResourceManager.GetString("HeaderTemplateUninstalling0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogCompletion0 {
            get {
                return ResourceManager.GetString("LogCompletion0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソリューションファイルを作成します。 {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogCreatingSolutionFile1 {
            get {
                return ResourceManager.GetString("LogCreatingSolutionFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました。
        ///* `ndext new` `ndext new-*` コマンドでNext Designのエクステンションが作成できます。
        ///* `dotnet new` コマンドでもエクステンションが作成できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogInstallationCompleted0 {
            get {
                return ResourceManager.GetString("LogInstallationCompleted0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パッケージ化を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogPackagingCompleted0 {
            get {
                return ResourceManager.GetString("LogPackagingCompleted0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に `{1}` を作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogProjectFileCreated2 {
            get {
                return ResourceManager.GetString("LogProjectFileCreated2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソリューションファイル `{0}` を検出しました。このファイルにプロジェクトを追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSolutionFileDetected1 {
            get {
                return ResourceManager.GetString("LogSolutionFileDetected1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクステンションをパッケージ化しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusPackagingExtension0 {
            get {
                return ResourceManager.GetString("StatusPackagingExtension0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ==========&gt; Packaging Project &lt;=========================
        ///[in] Target Project: {0}
        ///[in] Build Target: {1}
        ///[in] ND Version: {2} 
        ///======================================================== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusPackagingProject3 {
            get {
                return ResourceManager.GetString("StatusPackagingProject3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Design Extension Utility - Version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAppHeaderVersionInfo1 {
            get {
                return ResourceManager.GetString("TitleAppHeaderVersionInfo1", resourceCulture);
            }
        }
    }
}
